module NewTestUser
   
  def create_user(email, name, id)
    Fabricate(:user, email: email, name: name, id: id) 
  end

  def set_user_assest(usr)
    # * * * * * random generated samples * * * * *
    in_category  = Fabricate.times(10, :category, type: 10, user: usr)
    out_category = Fabricate.times(10, :category, type: 20, user: usr)
    tra_category = Fabricate.times(10, :category, type: 30, user: usr)

    in_category.each do |i|
      Fabricate.times(10, :subcategory, id_category: i.hash_key, user: usr)
    end
    out_category.each do |o|
      Fabricate.times(10, :subcategory, id_category: o.hash_key, user: usr)
    end
    tra_category.each do |t|
      Fabricate.times(10, :subcategory, id_category: t.hash_key, user: usr)
    end

    Fabricate.times(10, :payee, user: usr)
    Fabricate.times(10, :project, user: usr)
    Fabricate.times(2, :payment, user: usr, currency_code: 'TWD')

    Fabricate(:currency, currency_code: 'AED', rate: 3.674140127, currency_remark: 'UAE dirham ', sequence_status: -1, flag_path: 'UAE.png', user: usr)
    #Fabricate(:currency, currency_code: 'ANG', rate: 1.75, currency_remark: 'Netherlands Antillean Guilder', sequence_status: -1, flag_path: 'Netherlands.png', user: usr)
    Fabricate(:currency, currency_code: 'ARS', rate: 4.215, currency_remark: ' Argentinian Peso', sequence_status: -1, flag_path: 'Argentina.png', user: usr)
    #Fabricate(:currency, currency_code: 'AUD', rate: 0.9357, currency_remark: 'Australian Dollar', sequence_status: -1, flag_path: 'Australia.png', user: usr)
    Fabricate(:currency, currency_code: 'BDT', rate: 77.17, currency_remark: 'Bangladeshi Taka', sequence_status: -1, flag_path: 'Bangladesh.png', user: usr)
    #Fabricate(:currency, currency_code: 'BGN', rate: 1.3642, currency_remark: 'Bulgarian Lev', sequence_status: -1, flag_path: 'Bulgaria.png', user: usr)
    #Fabricate(:currency, currency_code: 'BHD', rate: 0.377, currency_remark: 'Bahraini Dinar', sequence_status: -1, flag_path: 'Bahrain.png', user: usr)
    #Fabricate(:currency, currency_code: 'BND', rate: 1.2854, currency_remark: 'Brunei Dollar', sequence_status: -1, flag_path: 'Brunei.png', user: usr)
    #Fabricate(:currency, currency_code: 'BOB', rate: 6.89, currency_remark: 'Bolivian Boliviano', sequence_status: -1, flag_path: 'Bolivia.png', user: usr)
    #Fabricate(:currency, currency_code: 'BRL', rate: 1.581, currency_remark: 'Brasilian Real', sequence_status: -1, flag_path: 'Brazil.png', user: usr)
    #Fabricate(:currency, currency_code: 'BWP', rate: 7.4294, currency_remark: 'Bostwanan Pula', sequence_status: -1, flag_path: 'Botswana.png', user: usr)
    #Fabricate(:currency, currency_code: 'CAD', rate: 0.969, currency_remark: 'Canadian Dollar', sequence_status: -1, flag_path: 'Canada.png', user: usr)
    #Fabricate(:currency, currency_code: 'CHF', rate: 0.8498, currency_remark: 'Swiss Franc', sequence_status: -1, flag_path: 'Switzerland.png', user: usr)
    #Fabricate(:currency, currency_code: 'CLP', rate: 508.4, currency_remark: 'Chilean Peso', sequence_status: -1, flag_path: 'Chile.png', user: usr)
    #Fabricate(:currency, currency_code: 'CNY', rate: 6.4814, currency_remark: 'Chinese Yuan Renminbi', sequence_status: -1, flag_path: 'China.png', user: usr)
    #Fabricate(:currency, currency_code: 'COP', rate: 1934.5, currency_remark: 'Colombian Peso', sequence_status: -1, flag_path: 'Colombia.png', user: usr)
    #Fabricate(:currency, currency_code: 'CRC', rate: 501.95, currency_remark: 'Costa Rican Colon', sequence_status: -1, flag_path: 'Costa Rica.png', user: usr)
    #Fabricate(:currency, currency_code: 'CZK', rate: 16.878, currency_remark: 'Czech Koruna', sequence_status: -1, flag_path: 'Czech.png', user: usr)
    #Fabricate(:currency, currency_code: 'DKK', rate: 5.2034, currency_remark: 'Danish Krone', sequence_status: -1, flag_path: 'Denmark.png', user: usr)
    #Fabricate(:currency, currency_code: 'DOP', rate: 38.41, currency_remark: 'Dominican Peso', sequence_status: -1, flag_path: 'Dominica.png', user: usr)
    #Fabricate(:currency, currency_code: 'DZD', rate: 74.71, currency_remark: 'Algerian Dinar', sequence_status: -1, flag_path: 'Algeria.png', user: usr)
    #Fabricate(:currency, currency_code: 'EEK', rate: 11.7303, currency_remark: 'Estonian Kroon', sequence_status: -1, flag_path: 'Estonia.png', user: usr)
    #Fabricate(:currency, currency_code: 'EGP', rate: 6.0057, currency_remark: 'Egyptian Pound', sequence_status: -1, flag_path: 'Egypt.png', user: usr)
    Fabricate(:currency, currency_code: 'EUR', rate: 0.75, currency_remark: 'Euro', sequence_status: -1, flag_path: 'Europe.png', user: usr)
    #Fabricate(:currency, currency_code: 'FJD', rate: 1.8159, currency_remark: 'Fijian Dollar', sequence_status: -1, flag_path: 'Fiji.png', user: usr)
    #Fabricate(:currency, currency_code: "GBP", rate:0.6136, currency_remark: "Pound Sterling", sequence_status:-1, flag_path: "Britain.png", user: usr)
    #Fabricate(:currency, currency_code: "HKD", rate:7.7855, currency_remark: "Hong Kong Dollar", sequence_status:-1, flag_path: "Hong_Kong.png", user: usr)
    #Fabricate(:currency, currency_code: "HNL", rate:18.92, currency_remark: "Honduran Lempira", sequence_status:-1, flag_path: "Honduras.png", user: usr)
    #Fabricate(:currency, currency_code: "HRK", rate:5.1624, currency_remark: "Croatian Kuna", sequence_status:-1, flag_path: "Croatia.png", user: usr)
    #Fabricate(:currency, currency_code: "HUF", rate:185.22, currency_remark: "Hungarian Forint", sequence_status:-1, flag_path: "Hungary.png", user: usr)
    #Fabricate(:currency, currency_code: "IDR", rate:8545, currency_remark: "Indonesian Rupiah", sequence_status:-1, flag_path: "Indonesia.png", user: usr)
    #Fabricate(:currency, currency_code: "ILS", rate:3.7587, currency_remark: "Israeli New Sheqel", sequence_status:-1, flag_path: "Israel.png", user: usr)
    #Fabricate(:currency, currency_code: "INR", rate:44.73, currency_remark: "Indian Rupee", sequence_status:-1, flag_path: "India.png", user: usr)
    Fabricate(:currency, currency_code: "JMD", rate:85.65, currency_remark: "Jamaican Dollar", sequence_status:-1, flag_path: "Jamaica.png", user: usr)
    #Fabricate(:currency, currency_code: "JOD", rate:0.709, currency_remark: "Jordanian Dinar", sequence_status:-1, flag_path: "Jordan.png", user: usr)
    #Fabricate(:currency, currency_code: "JPY", rate:80.74, currency_remark: "Japanese Yen", sequence_status:-1, flag_path: "Japan.png", user: usr)
    #Fabricate(:currency, currency_code: "KRW", rate:1083, currency_remark: "South Korean Won", sequence_status:-1, flag_path: "South_Korea.png", user: usr)
    #Fabricate(:currency, currency_code: "KWD", rate:0.277, currency_remark: "Kuwaiti Dinar", sequence_status:-1, flag_path: "Kuwait.png", user: usr)
    #Fabricate(:currency, currency_code: "KYD", rate:0.82, currency_remark: "Cayman Islands Dollar", sequence_status:-1, flag_path: "Cayman Islands.png", user: usr)
    #Fabricate(:currency, currency_code: "KZT", rate:147.67, currency_remark: "Kazakhstani Tenge", sequence_status:-1, flag_path: "Kazakhstan.png", user: usr)
    #Fabricate(:currency, currency_code: "LBP", rate:1505.5, currency_remark: "Lebanese Pound", sequence_status:-1, flag_path: "Lebanon.png", user: usr)
    #Fabricate(:currency, currency_code: "LKR", rate:113.89, currency_remark: "Sri Lankan Rupee", sequence_status:-1, flag_path: "Sri Lanka.png", user: usr)
    #Fabricate(:currency, currency_code: "LTL", rate:2.4086, currency_remark: "Lithuanian Litas", sequence_status:-1, flag_path: "Lithuania.png", user: usr)
    #Fabricate(:currency, currency_code: "LVL", rate:0.4943, currency_remark: "Latvian Lats", sequence_status:-1, flag_path: "Latvia.png", user: usr)
    #Fabricate(:currency, currency_code: "MAD", rate:8.3369, currency_remark: "Moroccan Dirham", sequence_status:-1, flag_path: "Morocco.png", user: usr)
    #Fabricate(:currency, currency_code: "MDL", rate:11.785, currency_remark: "Moldovan Leu", sequence_status:-1, flag_path: "Moldova.png", user: usr)
    #Fabricate(:currency, currency_code: "MKD", rate:45.625, currency_remark: "Macedonian Denar", sequence_status:-1, flag_path: "Macedonia.png", user: usr)
    #Fabricate(:currency, currency_code: "MUR", rate:28.05, currency_remark: "Mauritian Rupee", sequence_status:-1, flag_path: "Mauritius.png", user: usr)
    #Fabricate(:currency, currency_code: "MVR", rate:15.48, currency_remark: "Maldivian Rufiyaa", sequence_status:-1, flag_path: "Maldives.png", user: usr)
    #Fabricate(:currency, currency_code: "MXN", rate:11.8345, currency_remark: "Mexican Peso", sequence_status:-1, flag_path: "Mexico.png", user: usr)
    #Fabricate(:currency, currency_code: "MYR", rate:3.0323, currency_remark: "Malaysian Ringgit", sequence_status:-1, flag_path: "Malaysia.png", user: usr)
    #Fabricate(:currency, currency_code: "NAD", rate:8.045, currency_remark: "Namibian Dollar", sequence_status:-1, flag_path: "Namibia.png", user: usr)
    #Fabricate(:currency, currency_code: "NGN", rate:161.65, currency_remark: "Nigerian Naira", sequence_status:-1, flag_path: "Nigeria.png", user: usr)
    #Fabricate(:currency, currency_code: "NIO", rate:22.89, currency_remark: "Nicaraguan Córdoba", sequence_status:-1, flag_path: "Nicaragua.png", user: usr)
    #Fabricate(:currency, currency_code: "NOK", rate:5.4511, currency_remark: "Norwegian Krone", sequence_status:-1, flag_path: "Norway.png", user: usr)
    #Fabricate(:currency, currency_code: "NPR", rate:81.43, currency_remark: "Nepalese Rupee", sequence_status:-1, flag_path: "Nepal.png", user: usr)
    #Fabricate(:currency, currency_code: "NZD", rate:1.2282, currency_remark: "New Zealand Dollar", sequence_status:-1, flag_path: "New_Zealand.png", user: usr)
    #Fabricate(:currency, currency_code: "OMR", rate:0.385, currency_remark: "Omani Rial", sequence_status:-1, flag_path: "Oman.png", user: usr)
    #Fabricate(:currency, currency_code: "PEN", rate:2.698, currency_remark: "Peruvian Nuevo Sol", sequence_status:-1, flag_path: "Peru.png", user: usr)
    #Fabricate(:currency, currency_code: "PGK", rate:2.2272, currency_remark: "Papua New Guinean Kina", sequence_status:-1, flag_path: "Papua New Guinea.png", user: usr)
    #Fabricate(:currency, currency_code: "PHP", rate:43.48, currency_remark: "Philippine Peso", sequence_status:-1, flag_path: "Philippines.png", user: usr)
    #Fabricate(:currency, currency_code: "PKR", rate:89.45, currency_remark: "Pakistani Rupee", sequence_status:-1, flag_path: "Pakistan.png", user: usr)
    #Fabricate(:currency, currency_code: "PLN", rate:2.75, currency_remark: "Polish Zloty", sequence_status:-1, flag_path: "Poland.png", user: usr)
    #Fabricate(:currency, currency_code: "PYG", rate:4462, currency_remark: "Paraguayan Guarani", sequence_status:-1, flag_path: "Paraguay.png", user: usr)
    #Fabricate(:currency, currency_code: "QAR", rate:3.6415, currency_remark: "Qatari Rial", sequence_status:-1, flag_path: "Qatar.png", user: usr)
    #Fabricate(:currency, currency_code: "RON", rate:2.9143, currency_remark: "New Romanian Leu", sequence_status:-1, flag_path: "Romania.png", user: usr)
    #Fabricate(:currency, currency_code: "RSD", rate:77.4757, currency_remark: "Serbian Dinar", sequence_status:-1, flag_path: "Serbia(Yugoslavia).png", user: usr)
    #Fabricate(:currency, currency_code: "RUB", rate:27.9286, currency_remark: "Russian Rouble", sequence_status:-1, flag_path: "Russia.png", user: usr)
    #Fabricate(:currency, currency_code: "SAR", rate:3.7503, currency_remark: "Saudi Riyal", sequence_status:-1, flag_path: "Saudi Arabia.png", user: usr)
    #Fabricate(:currency, currency_code: "SCR", rate:12.65, currency_remark: "Seychellois Rupee", sequence_status:-1, flag_path: "Seychelles.png", user: usr)
    #Fabricate(:currency, currency_code: "SEK", rate:6.3688, currency_remark: "Swedish Krona", sequence_status:-1, flag_path: "Sweden.png", user: usr)
    #Fabricate(:currency, currency_code: "SGD", rate:1.2342, currency_remark: "Singapore Dollar", sequence_status:-1, flag_path: "Singapore.png", user: usr)
    #Fabricate(:currency, currency_code: "SKK", rate:22.4737, currency_remark: "Slovak Koruna", sequence_status:-1, flag_path: "Slovakia.png", user: usr)
    #Fabricate(:currency, currency_code: "SLL", rate:4400, currency_remark: "Sierra Leonean Leone", sequence_status:-1, flag_path: "Sierra Leone.png", user: usr)
    #Fabricate(:currency, currency_code: "SVC", rate:8.75, currency_remark: "Salvadoran Colón", sequence_status:-1, flag_path: "El Salvador.png", user: usr)
    #Fabricate(:currency, currency_code: "THB", rate:30.51, currency_remark: "Thai Baht", sequence_status:-1, flag_path: "Thailand.png", user: usr)
    #Fabricate(:currency, currency_code: "TND", rate:1.472, currency_remark: "Tunisian Dinar", sequence_status:-1, flag_path: "Tunisia.png", user: usr)
    #Fabricate(:currency, currency_code: "TRY", rate:1.5951, currency_remark: "Turkish Lira", sequence_status:-1, flag_path: "Turkey.png", user: usr)
    #Fabricate(:currency, currency_code: "TTD", rate:6.375, currency_remark: "Trinidad and Tobago Dollar", sequence_status:-1, flag_path: "Trinidad & Tobago.png", user: usr)
    Fabricate(:currency, currency_code: "TWD", rate:28.842, currency_remark: "New Taiwan Dollar", sequence_status:0, flag_path: "Taiwan.png", user: usr)
    #Fabricate(:currency, currency_code: "TZS", rate:1665, currency_remark: "Tanzanian Shilling", sequence_status:-1, flag_path: "Tanzania.png", user: usr)
    #Fabricate(:currency, currency_code: "UAH", rate:8.008, currency_remark: "Ukrainian Hryvnia", sequence_status:-1, flag_path: "Ukraine.png", user: usr)
    #Fabricate(:currency, currency_code: "UGX", rate:2557.5448, currency_remark: "Uganda Shilling", sequence_status:-1, flag_path: "Uganda.png", user: usr)
    Fabricate(:currency, currency_code: "USD", rate:1, currency_remark: "US Dollar", sequence_status:-1, flag_path: "America.png", user: usr)
    #Fabricate(:currency, currency_code: "UYU", rate:19.7, currency_remark: "Uruguayan Peso", sequence_status:-1, flag_path: "Uruguay.png", user: usr)
    #Fabricate(:currency, currency_code: "UZS", rate:1780.22, currency_remark: "Uzbekistan Som", sequence_status:-1, flag_path: "Uzbekistan.png", user: usr)
    #Fabricate(:currency, currency_code: "VEF", rate:4.2946, currency_remark: "Venezuelan Bolívar", sequence_status:-1, flag_path: "Venezuela.png", user: usr)
    Fabricate(:currency, currency_code: "VND", rate:21010, currency_remark: "Vietnamese Dong", sequence_status:-1, flag_path: "Viet Nam.png", user: usr)
    #Fabricate(:currency, currency_code: "XOF", rate:489.17, currency_remark: "CFA Franc BCEAO", sequence_status:-1, flag_path: "Togo.png", user: usr)
    Fabricate(:currency, currency_code: "YER", rate:217.87, currency_remark: "Yemeni Rial", sequence_status:-1, flag_path: "Yemen.png", user: usr)
    #Fabricate(:currency, currency_code: "ZAR", rate:6.8191, currency_remark: "South African Rand", sequence_status:-1, flag_path: "South_Africa.png", user: usr)
    #Fabricate(:currency, currency_code: "ZMK", rate:5085, currency_remark: "Zambian Kwacha", sequence_status:-1, flag_path: "Zambia.png", user: usr)
    #Fabricate(:currency, currency_code: "MOP", rate:7.99908, currency_remark: "Macau Pataca", sequence_status:-1, flag_path: "Macau.png", user: usr)
    #Fabricate(:currency, currency_code: "BYR", rate:8050.9743, currency_remark: "Belarussian Ruble", sequence_status:-1, flag_path: "Belarus.png", user: usr)
    #Fabricate(:currency, currency_code: "MNT", rate:1320, currency_remark: "Mongolia Tugrik", sequence_status:-1, flag_path: "Mongolia.png", user: usr)
    #Fabricate(:currency, currency_code: "GTQ", rate:7.778, currency_remark: "Guatemala Quetzal", sequence_status:-1, flag_path: "Guatemala.png", user: usr)
    #Fabricate(:currency, currency_code: "IRR", rate:12240, currency_remark: "Iranian Rial", sequence_status:-1, flag_path: "Iran.png", user: usr)
    #Fabricate(:currency, currency_code: "TJS", rate:4.7652, currency_remark: "Tajikistani somoni", sequence_status:-1, flag_path: "Tajikistan.png", user: usr)
    #Fabricate(:currency, currency_code: "GEL", rate:1.6204, currency_remark: "Georgian lari", sequence_status:-1, flag_path: "Georgia.png", user: usr)
    #Fabricate(:currency, currency_code: "MMK", rate:841, currency_remark: "Burmese kyat", sequence_status:-1, flag_path: "Burma.png", user: usr)
    #Fabricate(:currency, currency_code: "KHR", rate:4135.03, currency_remark: "Cambodian riel", sequence_status:-1, flag_path: "Cambodia.png", user: usr)
    #Fabricate(:currency, currency_code: "BAM", rate:1.57894, currency_remark: "Bosnia and Herzegovina", sequence_status:-1, flag_path: "Bosnia.png", user: usr)
    #Fabricate(:currency, currency_code: "GHS", rate:1.94499, currency_remark: "Ghana cedi", sequence_status:-1, flag_path: "Ghana.png", user: usr)
    #Fabricate(:currency, currency_code: "KES", rate:87.3515, currency_remark: "Kenyan shilling", sequence_status:-1, flag_path: "kenya.png", user: usr)
    #Fabricate(:currency, currency_code: "BTC", rate:1, currency_remark: "Bitcoin", sequence_status:-1, flag_path: "bitcoin.png", user: usr)
    #Fabricate(:currency, currency_code: "IQD", rate:1163.2, currency_remark: "Iraq, Dinar", sequence_status:-1, flag_path: "iraq.png", user: usr)
    #Fabricate(:currency, currency_code: "BBD", rate:2, currency_remark: "Barbadian Dollar", sequence_status:-1, flag_path: "barbados.png", user: usr)
    #Fabricate(:currency, currency_code: "AAA", rate:1, currency_remark: "Other Currency", sequence_status:-1, flag_path: "world.png", user: usr)

    # * * * * * generated targets * * * * *
    Fabricate(:payment, user: usr, currency_code: 'TWD', kind: 2, payment_name: 'Taishin Bank')
    Fabricate(:payment, user: usr, currency_code: 'USD', kind: 1, payment_name: 'Bank of America')
    Fabricate(:payment, user: usr, currency_code: 'EUR', kind: 0, payment_name: 'Deutsch Bank')

    stock = Fabricate(:category, user: usr, type: 10, category: 'stock investment')
    Fabricate(:subcategory, subcategory: "Buffet's choice", id_category: stock.hash_key, user: usr)
    Fabricate.times(10, :subcategory, id_category: stock.hash_key, user: usr)

    elect = Fabricate(:category, user: usr, type: 20, category: 'Electronics Equ')
    Fabricate(:subcategory, subcategory: "Apple's best", id_category: elect.hash_key, user: usr)
    Fabricate.times(10, :subcategory, id_category: elect.hash_key, user: usr)

    lover = Fabricate(:category, user: usr, type: 30, category: 'To my lover')
    Fabricate(:subcategory, subcategory: "miss Gina", id_category: lover.hash_key, user: usr)
    Fabricate.times(10, :subcategory, id_category: lover.hash_key, user: usr)

    Fabricate(:payee, payee_name: "Amazon", user: usr)
    Fabricate(:project, project_name: "Business", user: usr)

  end
end